version: '3'

services:
  db:
    image: postgres:14.5-alpine3.16
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - secrets.env

  redis:
    image: redis:7.0.4-alpine3.16
    restart: always

  app:
    image: nextcloud:24.0.5-fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - /mnt/data:/mnt/data
    depends_on:
      - db
      - redis
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
    env_file:
      - secrets.env

  web:
    build: ./web
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
      - /mnt/data:/mnt/data:ro
    environment:
      - VIRTUAL_HOST=beijaflor.es,www.beijaflor.es,links.beijaflor.es,cloud.beijaflor.es,blog.beijaflor.es
      - LETSENCRYPT_HOST=beijaflor.es,www.beijaflor.es,links.beijaflor.es,cloud.beijaflor.es,blog.beijaflor.es
      - LETSENCRYPT_EMAIL=rachel@beijaflor.es
    depends_on:
      - app
    networks:
      - proxy-tier

  cron:
    image: nextcloud:24.0.5-fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - /mnt/data:/mnt/data
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: nginxproxy/acme-companion:2.2.1
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - acme:/etc/acme.sh
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

# self signed
#  omgwtfssl:
#    image: paulczar/omgwtfssl
#    restart: "no"
#    volumes:
#      - certs:/certs
#    environment:
#      - SSL_SUBJECT=servhostname.local
#      - CA_SUBJECT=my@example.com
#      - SSL_KEY=/certs/servhostname.local.key
#      - SSL_CSR=/certs/servhostname.local.csr
#      - SSL_CERT=/certs/servhostname.local.crt
#    networks:
#      - proxy-tier

volumes:
  db:
  nextcloud:
  certs:
  acme:
  vhost.d:
  html:

networks:
  proxy-tier:
