version: '3'

services:
  db:
    image: postgres:14.5-alpine3.16
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - nextcloud_secrets.env

  redis:
    image: redis:7.0.4-alpine3.16
    restart: always

  nextcloud:
    image: nextcloud:24.0.6-fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - /mnt/data:/mnt/data
    depends_on:
      - db
      - redis
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
    env_file:
      - nextcloud_secrets.env

  dnd_wiki:
    build: ./dnd-wiki
    restart: always
    volumes:
      - dnd-wiki:/var/www/html
    depends_on:
      - db

  nextcloud_cron:
    image: nextcloud:24.0.6-fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - /mnt/data:/mnt/data
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  web:
    build: ./web
    restart: always
    volumes:
      - /opt/repos/beijaflor.es:/var/www/html/beijaflor.es:ro
      - /opt/repos/links.beijaflor.es:/var/www/html/links.beijaflor.es:ro
      - nextcloud:/var/www/html/cloud.beijaflor.es:ro
      - dnd-wiki:/var/www/html/dnd.beijaflor.es:ro
      - /mnt/data:/mnt/data:ro
    environment:
      - VIRTUAL_HOST=beijaflor.es,www.beijaflor.es,links.beijaflor.es,cloud.beijaflor.es,dnd.beijaflor.es
      - LETSENCRYPT_HOST=beijaflor.es,www.beijaflor.es,links.beijaflor.es,cloud.beijaflor.es,dnd.beijaflor.es
      - LETSENCRYPT_EMAIL=rachel@beijaflor.es
    depends_on:
      - nextcloud
    networks:
      - default
      - proxy-tier

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt_companion:
    image: nginxproxy/acme-companion:2.2.1
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - acme:/etc/acme.sh
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

  # self signed
  # omgwtfssl:
  #   image: paulczar/omgwtfssl
  #   restart: "no"
  #   volumes:
  #     - certs:/certs
  #   environment:
  #     - SSL_SUBJECT=beijaflor.es
  #     - CA_SUBJECT=rachel@beijaflor.es
  #     - SSL_KEY=/certs/beijaflor.es.key
  #     - SSL_CSR=/certs/beijaflor.es.csr
  #     - SSL_CERT=/certs/beijaflor.es.crt
  #   networks:
  #     - proxy-tier

volumes:
  db:
  nextcloud:
  dnd-wiki:
  certs:
  acme:
  vhost.d:
  html:

networks:
  proxy-tier:
