# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Deploy_to_Production:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Cloning repository
        uses: actions/checkout@v2
        with: 
          submodules: 'true'
 
      - name: Install SSH private key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_ed25519
          echo "${{ secrets.DEPLOY_SSH_PRIV_KEY }}" > ~/.ssh/id_ed25519

      - name: Test SSH connection to production server
        run: |
          echo "${SSH_KNOWN_HOSTS}" | tee ~/.ssh/known_hosts
          ssh github@${DEST_HOST} whoami

      - name: Deploy to production
        run: |
          ssh github@${DEST_HOST} mkdir -p ${DEST_DIR}
          rsync -avz --delete --safe-links --exclude=.git ./ github@${DEST_HOST}:${DEST_DIR}
          ssh github@${DEST_HOST} <<EOF
              install -m 600 /home/github/nextcloud_secrets.env ${DEST_DIR}/nextcloud_secrets.env
              cd ${DEST_DIR}
              sudo docker compose pull && sudo docker compose build && sudo docker compose up -d
          EOF

      - name: Apply migrations and final touch-ups
          ssh github@${DEST_HOST} <<EOF
              cd ${DEST_DIR}
              sudo docker compose exec -u www-data nextcloud php occ db:add-missing-columns -n
              sudo docker compose exec -u www-data nextcloud php occ db:add-missing-indices -n
              sudo docker compose exec -u www-data nextcloud php occ db:add-missing-primary-keys -n
          EOF

env: 
  # Destination hostname
  DEST_HOST: beijaflor.es
  # Destination directory
  DEST_DIR: /opt/repos/beijaflor-infra
  # ssh_known_hosts file
  SSH_KNOWN_HOSTS: |-
    beijaflor.es ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMgBHuMbo4un1kUg964oEWqZ71h503GcPxbCwZQLMq8T 

#  vim: set ts=4 sw=2 tw=88 et :
